/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CaseStatus = IDL.Variant({
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'dataIngestion' : IDL.Null,
  'analysis' : IDL.Null,
  'draft' : IDL.Null,
});
export const Sector = IDL.Variant({
  'it' : IDL.Null,
  'realEstate' : IDL.Null,
  'auto' : IDL.Null,
  'fmcg' : IDL.Null,
  'chemicals' : IDL.Null,
  'steel' : IDL.Null,
  'infrastructure' : IDL.Null,
  'textile' : IDL.Null,
  'pharma' : IDL.Null,
});
export const Recommendation = IDL.Variant({
  'reject' : IDL.Null,
  'approve' : IDL.Null,
  'conditionalApprove' : IDL.Null,
});
export const CAMReport = IDL.Record({
  'keyStrengths' : IDL.Vec(IDL.Text),
  'keyRisks' : IDL.Vec(IDL.Text),
  'recommendedLimitCrores' : IDL.Nat,
  'interestRateMax' : IDL.Float64,
  'interestRateMin' : IDL.Float64,
  'executiveSummary' : IDL.Text,
  'riskPremiumBps' : IDL.Nat,
  'conditions' : IDL.Vec(IDL.Text),
  'recommendation' : Recommendation,
});
export const RiskBand = IDL.Variant({
  'a' : IDL.Null,
  'b' : IDL.Null,
  'd' : IDL.Null,
  'aa' : IDL.Null,
  'bb' : IDL.Null,
  'aaa' : IDL.Null,
  'bbb' : IDL.Null,
  'ccc' : IDL.Null,
});
export const CreditScore = IDL.Record({
  'roe' : IDL.Float64,
  'netProfitMargin' : IDL.Float64,
  'overallScore' : IDL.Nat,
  'currentRatio' : IDL.Float64,
  'interestCoverageRatio' : IDL.Float64,
  'dscr' : IDL.Float64,
  'riskBand' : RiskBand,
  'managementQuality' : IDL.Nat,
  'debtToEquity' : IDL.Float64,
  'legalRiskScore' : IDL.Nat,
  'industryOutlook' : IDL.Nat,
  'complianceScore' : IDL.Nat,
  'financialHealth' : IDL.Nat,
});
export const SignalCategory = IDL.Variant({
  'compliance' : IDL.Null,
  'legal' : IDL.Null,
  'market' : IDL.Null,
  'financial' : IDL.Null,
  'management' : IDL.Null,
});
export const Severity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const Time = IDL.Int;
export const EarlyWarningSignal = IDL.Record({
  'description' : IDL.Text,
  'category' : SignalCategory,
  'severity' : Severity,
  'detectedDate' : Time,
});
export const SourceStatusEnum = IDL.Variant({
  'pending' : IDL.Null,
  'done' : IDL.Null,
  'error' : IDL.Null,
  'uploaded' : IDL.Null,
  'processing' : IDL.Null,
});
export const SourceCategory = IDL.Variant({
  'gst' : IDL.Null,
  'itr' : IDL.Null,
  'legalDisputes' : IDL.Null,
  'siteVisitNotes' : IDL.Null,
  'ratingReport' : IDL.Null,
  'boardMinutes' : IDL.Null,
  'financialStatements' : IDL.Null,
  'managementInterviewNotes' : IDL.Null,
  'shareholdingPattern' : IDL.Null,
  'annualReport' : IDL.Null,
  'newsIntelligence' : IDL.Null,
  'bankStatements' : IDL.Null,
  'mcaFilings' : IDL.Null,
});
export const SourceStatus = IDL.Record({
  'status' : SourceStatusEnum,
  'name' : SourceCategory,
  'notes' : IDL.Opt(IDL.Text),
});
export const DataIngestionStatus = IDL.Record({
  'filings' : IDL.Vec(SourceStatus),
});
export const CreditCase = IDL.Record({
  'id' : IDL.Nat,
  'cin' : IDL.Text,
  'status' : CaseStatus,
  'camReport' : IDL.Opt(CAMReport),
  'sector' : Sector,
  'creditScore' : IDL.Opt(CreditScore),
  'tenureMonths' : IDL.Nat,
  'earlyWarningSignals' : IDL.Opt(IDL.Vec(EarlyWarningSignal)),
  'createdTimestamp' : Time,
  'companyName' : IDL.Text,
  'dataIngestion' : IDL.Opt(DataIngestionStatus),
  'loanAmountCrores' : IDL.Nat,
  'assignedAnalyst' : IDL.Opt(IDL.Principal),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'department' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignAnalyst' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeCaseStatus' : IDL.Func([IDL.Nat, CaseStatus], [], []),
  'createCreditCase' : IDL.Func(
      [IDL.Text, IDL.Text, Sector, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'filterCasesBySector' : IDL.Func([Sector], [IDL.Vec(CreditCase)], ['query']),
  'filterCasesByStatus' : IDL.Func(
      [CaseStatus],
      [IDL.Vec(CreditCase)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCreditCase' : IDL.Func([IDL.Nat], [CreditCase], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCases' : IDL.Func([], [IDL.Vec(CreditCase)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'triggerAnalysis' : IDL.Func(
      [IDL.Nat, CreditScore, IDL.Opt(IDL.Vec(EarlyWarningSignal)), CAMReport],
      [],
      [],
    ),
  'updateDataIngestion' : IDL.Func([IDL.Nat, DataIngestionStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CaseStatus = IDL.Variant({
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'dataIngestion' : IDL.Null,
    'analysis' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Sector = IDL.Variant({
    'it' : IDL.Null,
    'realEstate' : IDL.Null,
    'auto' : IDL.Null,
    'fmcg' : IDL.Null,
    'chemicals' : IDL.Null,
    'steel' : IDL.Null,
    'infrastructure' : IDL.Null,
    'textile' : IDL.Null,
    'pharma' : IDL.Null,
  });
  const Recommendation = IDL.Variant({
    'reject' : IDL.Null,
    'approve' : IDL.Null,
    'conditionalApprove' : IDL.Null,
  });
  const CAMReport = IDL.Record({
    'keyStrengths' : IDL.Vec(IDL.Text),
    'keyRisks' : IDL.Vec(IDL.Text),
    'recommendedLimitCrores' : IDL.Nat,
    'interestRateMax' : IDL.Float64,
    'interestRateMin' : IDL.Float64,
    'executiveSummary' : IDL.Text,
    'riskPremiumBps' : IDL.Nat,
    'conditions' : IDL.Vec(IDL.Text),
    'recommendation' : Recommendation,
  });
  const RiskBand = IDL.Variant({
    'a' : IDL.Null,
    'b' : IDL.Null,
    'd' : IDL.Null,
    'aa' : IDL.Null,
    'bb' : IDL.Null,
    'aaa' : IDL.Null,
    'bbb' : IDL.Null,
    'ccc' : IDL.Null,
  });
  const CreditScore = IDL.Record({
    'roe' : IDL.Float64,
    'netProfitMargin' : IDL.Float64,
    'overallScore' : IDL.Nat,
    'currentRatio' : IDL.Float64,
    'interestCoverageRatio' : IDL.Float64,
    'dscr' : IDL.Float64,
    'riskBand' : RiskBand,
    'managementQuality' : IDL.Nat,
    'debtToEquity' : IDL.Float64,
    'legalRiskScore' : IDL.Nat,
    'industryOutlook' : IDL.Nat,
    'complianceScore' : IDL.Nat,
    'financialHealth' : IDL.Nat,
  });
  const SignalCategory = IDL.Variant({
    'compliance' : IDL.Null,
    'legal' : IDL.Null,
    'market' : IDL.Null,
    'financial' : IDL.Null,
    'management' : IDL.Null,
  });
  const Severity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Time = IDL.Int;
  const EarlyWarningSignal = IDL.Record({
    'description' : IDL.Text,
    'category' : SignalCategory,
    'severity' : Severity,
    'detectedDate' : Time,
  });
  const SourceStatusEnum = IDL.Variant({
    'pending' : IDL.Null,
    'done' : IDL.Null,
    'error' : IDL.Null,
    'uploaded' : IDL.Null,
    'processing' : IDL.Null,
  });
  const SourceCategory = IDL.Variant({
    'gst' : IDL.Null,
    'itr' : IDL.Null,
    'legalDisputes' : IDL.Null,
    'siteVisitNotes' : IDL.Null,
    'ratingReport' : IDL.Null,
    'boardMinutes' : IDL.Null,
    'financialStatements' : IDL.Null,
    'managementInterviewNotes' : IDL.Null,
    'shareholdingPattern' : IDL.Null,
    'annualReport' : IDL.Null,
    'newsIntelligence' : IDL.Null,
    'bankStatements' : IDL.Null,
    'mcaFilings' : IDL.Null,
  });
  const SourceStatus = IDL.Record({
    'status' : SourceStatusEnum,
    'name' : SourceCategory,
    'notes' : IDL.Opt(IDL.Text),
  });
  const DataIngestionStatus = IDL.Record({ 'filings' : IDL.Vec(SourceStatus) });
  const CreditCase = IDL.Record({
    'id' : IDL.Nat,
    'cin' : IDL.Text,
    'status' : CaseStatus,
    'camReport' : IDL.Opt(CAMReport),
    'sector' : Sector,
    'creditScore' : IDL.Opt(CreditScore),
    'tenureMonths' : IDL.Nat,
    'earlyWarningSignals' : IDL.Opt(IDL.Vec(EarlyWarningSignal)),
    'createdTimestamp' : Time,
    'companyName' : IDL.Text,
    'dataIngestion' : IDL.Opt(DataIngestionStatus),
    'loanAmountCrores' : IDL.Nat,
    'assignedAnalyst' : IDL.Opt(IDL.Principal),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'department' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignAnalyst' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeCaseStatus' : IDL.Func([IDL.Nat, CaseStatus], [], []),
    'createCreditCase' : IDL.Func(
        [IDL.Text, IDL.Text, Sector, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'filterCasesBySector' : IDL.Func(
        [Sector],
        [IDL.Vec(CreditCase)],
        ['query'],
      ),
    'filterCasesByStatus' : IDL.Func(
        [CaseStatus],
        [IDL.Vec(CreditCase)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCreditCase' : IDL.Func([IDL.Nat], [CreditCase], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCases' : IDL.Func([], [IDL.Vec(CreditCase)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'triggerAnalysis' : IDL.Func(
        [IDL.Nat, CreditScore, IDL.Opt(IDL.Vec(EarlyWarningSignal)), CAMReport],
        [],
        [],
      ),
    'updateDataIngestion' : IDL.Func([IDL.Nat, DataIngestionStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };