/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CAMReport {
  'keyStrengths' : Array<string>,
  'keyRisks' : Array<string>,
  'recommendedLimitCrores' : bigint,
  'interestRateMax' : number,
  'interestRateMin' : number,
  'executiveSummary' : string,
  'riskPremiumBps' : bigint,
  'conditions' : Array<string>,
  'recommendation' : Recommendation,
}
export type CaseStatus = { 'completed' : null } |
  { 'rejected' : null } |
  { 'dataIngestion' : null } |
  { 'analysis' : null } |
  { 'draft' : null };
export interface CreditCase {
  'id' : bigint,
  'cin' : string,
  'status' : CaseStatus,
  'camReport' : [] | [CAMReport],
  'sector' : Sector,
  'creditScore' : [] | [CreditScore],
  'tenureMonths' : bigint,
  'earlyWarningSignals' : [] | [Array<EarlyWarningSignal>],
  'createdTimestamp' : Time,
  'companyName' : string,
  'dataIngestion' : [] | [DataIngestionStatus],
  'loanAmountCrores' : bigint,
  'assignedAnalyst' : [] | [Principal],
}
export interface CreditScore {
  'roe' : number,
  'netProfitMargin' : number,
  'overallScore' : bigint,
  'currentRatio' : number,
  'interestCoverageRatio' : number,
  'dscr' : number,
  'riskBand' : RiskBand,
  'managementQuality' : bigint,
  'debtToEquity' : number,
  'legalRiskScore' : bigint,
  'industryOutlook' : bigint,
  'complianceScore' : bigint,
  'financialHealth' : bigint,
}
export interface DataIngestionStatus { 'filings' : Array<SourceStatus> }
export interface EarlyWarningSignal {
  'description' : string,
  'category' : SignalCategory,
  'severity' : Severity,
  'detectedDate' : Time,
}
export type Recommendation = { 'reject' : null } |
  { 'approve' : null } |
  { 'conditionalApprove' : null };
export type RiskBand = { 'a' : null } |
  { 'b' : null } |
  { 'd' : null } |
  { 'aa' : null } |
  { 'bb' : null } |
  { 'aaa' : null } |
  { 'bbb' : null } |
  { 'ccc' : null };
export type Sector = { 'it' : null } |
  { 'realEstate' : null } |
  { 'auto' : null } |
  { 'fmcg' : null } |
  { 'chemicals' : null } |
  { 'steel' : null } |
  { 'infrastructure' : null } |
  { 'textile' : null } |
  { 'pharma' : null };
export type Severity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type SignalCategory = { 'compliance' : null } |
  { 'legal' : null } |
  { 'market' : null } |
  { 'financial' : null } |
  { 'management' : null };
export type SourceCategory = { 'gst' : null } |
  { 'itr' : null } |
  { 'legalDisputes' : null } |
  { 'siteVisitNotes' : null } |
  { 'ratingReport' : null } |
  { 'boardMinutes' : null } |
  { 'financialStatements' : null } |
  { 'managementInterviewNotes' : null } |
  { 'shareholdingPattern' : null } |
  { 'annualReport' : null } |
  { 'newsIntelligence' : null } |
  { 'bankStatements' : null } |
  { 'mcaFilings' : null };
export interface SourceStatus {
  'status' : SourceStatusEnum,
  'name' : SourceCategory,
  'notes' : [] | [string],
}
export type SourceStatusEnum = { 'pending' : null } |
  { 'done' : null } |
  { 'error' : null } |
  { 'uploaded' : null } |
  { 'processing' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'department' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignAnalyst' : ActorMethod<[bigint, Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeCaseStatus' : ActorMethod<[bigint, CaseStatus], undefined>,
  'createCreditCase' : ActorMethod<
    [string, string, Sector, bigint, bigint],
    bigint
  >,
  'filterCasesBySector' : ActorMethod<[Sector], Array<CreditCase>>,
  'filterCasesByStatus' : ActorMethod<[CaseStatus], Array<CreditCase>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCreditCase' : ActorMethod<[bigint], CreditCase>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCases' : ActorMethod<[], Array<CreditCase>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'triggerAnalysis' : ActorMethod<
    [bigint, CreditScore, [] | [Array<EarlyWarningSignal>], CAMReport],
    undefined
  >,
  'updateDataIngestion' : ActorMethod<[bigint, DataIngestionStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];