/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DataIngestionStatus {
    filings: Array<SourceStatus>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SourceStatus {
    status: SourceStatusEnum;
    name: SourceCategory;
    notes?: string;
}
export interface CreditScore {
    roe: number;
    netProfitMargin: number;
    overallScore: bigint;
    currentRatio: number;
    interestCoverageRatio: number;
    dscr: number;
    riskBand: RiskBand;
    managementQuality: bigint;
    debtToEquity: number;
    legalRiskScore: bigint;
    industryOutlook: bigint;
    complianceScore: bigint;
    financialHealth: bigint;
}
export interface EarlyWarningSignal {
    description: string;
    category: SignalCategory;
    severity: Severity;
    detectedDate: Time;
}
export interface CreditCase {
    id: bigint;
    cin: string;
    status: CaseStatus;
    camReport?: CAMReport;
    sector: Sector;
    creditScore?: CreditScore;
    tenureMonths: bigint;
    earlyWarningSignals?: Array<EarlyWarningSignal>;
    createdTimestamp: Time;
    companyName: string;
    dataIngestion?: DataIngestionStatus;
    loanAmountCrores: bigint;
    assignedAnalyst?: Principal;
}
export interface CAMReport {
    keyStrengths: Array<string>;
    keyRisks: Array<string>;
    recommendedLimitCrores: bigint;
    interestRateMax: number;
    interestRateMin: number;
    executiveSummary: string;
    riskPremiumBps: bigint;
    conditions: Array<string>;
    recommendation: Recommendation;
}
export interface UserProfile {
    name: string;
    department: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum CaseStatus {
    completed = "completed",
    rejected = "rejected",
    dataIngestion = "dataIngestion",
    analysis = "analysis",
    draft = "draft"
}
export enum Recommendation {
    reject = "reject",
    approve = "approve",
    conditionalApprove = "conditionalApprove"
}
export enum RiskBand {
    a = "a",
    b = "b",
    d = "d",
    aa = "aa",
    bb = "bb",
    aaa = "aaa",
    bbb = "bbb",
    ccc = "ccc"
}
export enum Sector {
    it = "it",
    realEstate = "realEstate",
    auto = "auto",
    fmcg = "fmcg",
    chemicals = "chemicals",
    steel = "steel",
    infrastructure = "infrastructure",
    textile = "textile",
    pharma = "pharma"
}
export enum Severity {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum SignalCategory {
    compliance = "compliance",
    legal = "legal",
    market = "market",
    financial = "financial",
    management = "management"
}
export enum SourceCategory {
    gst = "gst",
    itr = "itr",
    legalDisputes = "legalDisputes",
    siteVisitNotes = "siteVisitNotes",
    ratingReport = "ratingReport",
    boardMinutes = "boardMinutes",
    financialStatements = "financialStatements",
    managementInterviewNotes = "managementInterviewNotes",
    shareholdingPattern = "shareholdingPattern",
    annualReport = "annualReport",
    newsIntelligence = "newsIntelligence",
    bankStatements = "bankStatements",
    mcaFilings = "mcaFilings"
}
export enum SourceStatusEnum {
    pending = "pending",
    done = "done",
    error = "error",
    uploaded = "uploaded",
    processing = "processing"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignAnalyst(caseId: bigint, analyst: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    changeCaseStatus(caseId: bigint, status: CaseStatus): Promise<void>;
    createCreditCase(companyName: string, cin: string, sector: Sector, loanAmountCrores: bigint, tenureMonths: bigint): Promise<bigint>;
    filterCasesBySector(sector: Sector): Promise<Array<CreditCase>>;
    filterCasesByStatus(status: CaseStatus): Promise<Array<CreditCase>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCreditCase(caseId: bigint): Promise<CreditCase>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listCases(): Promise<Array<CreditCase>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    triggerAnalysis(caseId: bigint, creditScore: CreditScore, earlyWarningSignals: Array<EarlyWarningSignal> | null, camReport: CAMReport): Promise<void>;
    updateDataIngestion(caseId: bigint, dataIngestion: DataIngestionStatus): Promise<void>;
}
import type { CAMReport as _CAMReport, CaseStatus as _CaseStatus, CreditCase as _CreditCase, CreditScore as _CreditScore, DataIngestionStatus as _DataIngestionStatus, EarlyWarningSignal as _EarlyWarningSignal, Recommendation as _Recommendation, RiskBand as _RiskBand, Sector as _Sector, Severity as _Severity, SignalCategory as _SignalCategory, SourceCategory as _SourceCategory, SourceStatus as _SourceStatus, SourceStatusEnum as _SourceStatusEnum, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignAnalyst(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignAnalyst(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignAnalyst(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async changeCaseStatus(arg0: bigint, arg1: CaseStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changeCaseStatus(arg0, to_candid_CaseStatus_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeCaseStatus(arg0, to_candid_CaseStatus_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCreditCase(arg0: string, arg1: string, arg2: Sector, arg3: bigint, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCreditCase(arg0, arg1, to_candid_Sector_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCreditCase(arg0, arg1, to_candid_Sector_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async filterCasesBySector(arg0: Sector): Promise<Array<CreditCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterCasesBySector(to_candid_Sector_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterCasesBySector(to_candid_Sector_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterCasesByStatus(arg0: CaseStatus): Promise<Array<CreditCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterCasesByStatus(to_candid_CaseStatus_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterCasesByStatus(to_candid_CaseStatus_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreditCase(arg0: bigint): Promise<CreditCase> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreditCase(arg0);
                return from_candid_CreditCase_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreditCase(arg0);
            return from_candid_CreditCase_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCases(): Promise<Array<CreditCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCases();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCases();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async triggerAnalysis(arg0: bigint, arg1: CreditScore, arg2: Array<EarlyWarningSignal> | null, arg3: CAMReport): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerAnalysis(arg0, to_candid_CreditScore_n54(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n58(this._uploadFile, this._downloadFile, arg2), to_candid_CAMReport_n66(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerAnalysis(arg0, to_candid_CreditScore_n54(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n58(this._uploadFile, this._downloadFile, arg2), to_candid_CAMReport_n66(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateDataIngestion(arg0: bigint, arg1: DataIngestionStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDataIngestion(arg0, to_candid_DataIngestionStatus_n70(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDataIngestion(arg0, to_candid_DataIngestionStatus_n70(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CAMReport_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CAMReport): CAMReport {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_CaseStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaseStatus): CaseStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_CreditCase_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreditCase): CreditCase {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_CreditScore_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreditScore): CreditScore {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_DataIngestionStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DataIngestionStatus): DataIngestionStatus {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_EarlyWarningSignal_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EarlyWarningSignal): EarlyWarningSignal {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Recommendation_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recommendation): Recommendation {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_RiskBand_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskBand): RiskBand {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Sector_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sector): Sector {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Severity_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_SignalCategory_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalCategory): SignalCategory {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_SourceCategory_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SourceCategory): SourceCategory {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_SourceStatusEnum_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SourceStatusEnum): SourceStatusEnum {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_SourceStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SourceStatus): SourceStatus {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CAMReport]): CAMReport | null {
    return value.length === 0 ? null : from_candid_CAMReport_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CreditScore]): CreditScore | null {
    return value.length === 0 ? null : from_candid_CreditScore_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_EarlyWarningSignal>]): Array<EarlyWarningSignal> | null {
    return value.length === 0 ? null : from_candid_vec_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DataIngestionStatus]): DataIngestionStatus | null {
    return value.length === 0 ? null : from_candid_DataIngestionStatus_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    cin: string;
    status: _CaseStatus;
    camReport: [] | [_CAMReport];
    sector: _Sector;
    creditScore: [] | [_CreditScore];
    tenureMonths: bigint;
    earlyWarningSignals: [] | [Array<_EarlyWarningSignal>];
    createdTimestamp: _Time;
    companyName: string;
    dataIngestion: [] | [_DataIngestionStatus];
    loanAmountCrores: bigint;
    assignedAnalyst: [] | [Principal];
}): {
    id: bigint;
    cin: string;
    status: CaseStatus;
    camReport?: CAMReport;
    sector: Sector;
    creditScore?: CreditScore;
    tenureMonths: bigint;
    earlyWarningSignals?: Array<EarlyWarningSignal>;
    createdTimestamp: Time;
    companyName: string;
    dataIngestion?: DataIngestionStatus;
    loanAmountCrores: bigint;
    assignedAnalyst?: Principal;
} {
    return {
        id: value.id,
        cin: value.cin,
        status: from_candid_CaseStatus_n17(_uploadFile, _downloadFile, value.status),
        camReport: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.camReport)),
        sector: from_candid_Sector_n24(_uploadFile, _downloadFile, value.sector),
        creditScore: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.creditScore)),
        tenureMonths: value.tenureMonths,
        earlyWarningSignals: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.earlyWarningSignals)),
        createdTimestamp: value.createdTimestamp,
        companyName: value.companyName,
        dataIngestion: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.dataIngestion)),
        loanAmountCrores: value.loanAmountCrores,
        assignedAnalyst: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.assignedAnalyst))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    keyStrengths: Array<string>;
    keyRisks: Array<string>;
    recommendedLimitCrores: bigint;
    interestRateMax: number;
    interestRateMin: number;
    executiveSummary: string;
    riskPremiumBps: bigint;
    conditions: Array<string>;
    recommendation: _Recommendation;
}): {
    keyStrengths: Array<string>;
    keyRisks: Array<string>;
    recommendedLimitCrores: bigint;
    interestRateMax: number;
    interestRateMin: number;
    executiveSummary: string;
    riskPremiumBps: bigint;
    conditions: Array<string>;
    recommendation: Recommendation;
} {
    return {
        keyStrengths: value.keyStrengths,
        keyRisks: value.keyRisks,
        recommendedLimitCrores: value.recommendedLimitCrores,
        interestRateMax: value.interestRateMax,
        interestRateMin: value.interestRateMin,
        executiveSummary: value.executiveSummary,
        riskPremiumBps: value.riskPremiumBps,
        conditions: value.conditions,
        recommendation: from_candid_Recommendation_n22(_uploadFile, _downloadFile, value.recommendation)
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    roe: number;
    netProfitMargin: number;
    overallScore: bigint;
    currentRatio: number;
    interestCoverageRatio: number;
    dscr: number;
    riskBand: _RiskBand;
    managementQuality: bigint;
    debtToEquity: number;
    legalRiskScore: bigint;
    industryOutlook: bigint;
    complianceScore: bigint;
    financialHealth: bigint;
}): {
    roe: number;
    netProfitMargin: number;
    overallScore: bigint;
    currentRatio: number;
    interestCoverageRatio: number;
    dscr: number;
    riskBand: RiskBand;
    managementQuality: bigint;
    debtToEquity: number;
    legalRiskScore: bigint;
    industryOutlook: bigint;
    complianceScore: bigint;
    financialHealth: bigint;
} {
    return {
        roe: value.roe,
        netProfitMargin: value.netProfitMargin,
        overallScore: value.overallScore,
        currentRatio: value.currentRatio,
        interestCoverageRatio: value.interestCoverageRatio,
        dscr: value.dscr,
        riskBand: from_candid_RiskBand_n29(_uploadFile, _downloadFile, value.riskBand),
        managementQuality: value.managementQuality,
        debtToEquity: value.debtToEquity,
        legalRiskScore: value.legalRiskScore,
        industryOutlook: value.industryOutlook,
        complianceScore: value.complianceScore,
        financialHealth: value.financialHealth
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description: string;
    category: _SignalCategory;
    severity: _Severity;
    detectedDate: _Time;
}): {
    description: string;
    category: SignalCategory;
    severity: Severity;
    detectedDate: Time;
} {
    return {
        description: value.description,
        category: from_candid_SignalCategory_n35(_uploadFile, _downloadFile, value.category),
        severity: from_candid_Severity_n37(_uploadFile, _downloadFile, value.severity),
        detectedDate: value.detectedDate
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    filings: Array<_SourceStatus>;
}): {
    filings: Array<SourceStatus>;
} {
    return {
        filings: from_candid_vec_n42(_uploadFile, _downloadFile, value.filings)
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SourceStatusEnum;
    name: _SourceCategory;
    notes: [] | [string];
}): {
    status: SourceStatusEnum;
    name: SourceCategory;
    notes?: string;
} {
    return {
        status: from_candid_SourceStatusEnum_n45(_uploadFile, _downloadFile, value.status),
        name: from_candid_SourceCategory_n47(_uploadFile, _downloadFile, value.name),
        notes: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    rejected: null;
} | {
    dataIngestion: null;
} | {
    analysis: null;
} | {
    draft: null;
}): CaseStatus {
    return "completed" in value ? CaseStatus.completed : "rejected" in value ? CaseStatus.rejected : "dataIngestion" in value ? CaseStatus.dataIngestion : "analysis" in value ? CaseStatus.analysis : "draft" in value ? CaseStatus.draft : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reject: null;
} | {
    approve: null;
} | {
    conditionalApprove: null;
}): Recommendation {
    return "reject" in value ? Recommendation.reject : "approve" in value ? Recommendation.approve : "conditionalApprove" in value ? Recommendation.conditionalApprove : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    it: null;
} | {
    realEstate: null;
} | {
    auto: null;
} | {
    fmcg: null;
} | {
    chemicals: null;
} | {
    steel: null;
} | {
    infrastructure: null;
} | {
    textile: null;
} | {
    pharma: null;
}): Sector {
    return "it" in value ? Sector.it : "realEstate" in value ? Sector.realEstate : "auto" in value ? Sector.auto : "fmcg" in value ? Sector.fmcg : "chemicals" in value ? Sector.chemicals : "steel" in value ? Sector.steel : "infrastructure" in value ? Sector.infrastructure : "textile" in value ? Sector.textile : "pharma" in value ? Sector.pharma : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    a: null;
} | {
    b: null;
} | {
    d: null;
} | {
    aa: null;
} | {
    bb: null;
} | {
    aaa: null;
} | {
    bbb: null;
} | {
    ccc: null;
}): RiskBand {
    return "a" in value ? RiskBand.a : "b" in value ? RiskBand.b : "d" in value ? RiskBand.d : "aa" in value ? RiskBand.aa : "bb" in value ? RiskBand.bb : "aaa" in value ? RiskBand.aaa : "bbb" in value ? RiskBand.bbb : "ccc" in value ? RiskBand.ccc : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    compliance: null;
} | {
    legal: null;
} | {
    market: null;
} | {
    financial: null;
} | {
    management: null;
}): SignalCategory {
    return "compliance" in value ? SignalCategory.compliance : "legal" in value ? SignalCategory.legal : "market" in value ? SignalCategory.market : "financial" in value ? SignalCategory.financial : "management" in value ? SignalCategory.management : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): Severity {
    return "low" in value ? Severity.low : "high" in value ? Severity.high : "critical" in value ? Severity.critical : "medium" in value ? Severity.medium : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    done: null;
} | {
    error: null;
} | {
    uploaded: null;
} | {
    processing: null;
}): SourceStatusEnum {
    return "pending" in value ? SourceStatusEnum.pending : "done" in value ? SourceStatusEnum.done : "error" in value ? SourceStatusEnum.error : "uploaded" in value ? SourceStatusEnum.uploaded : "processing" in value ? SourceStatusEnum.processing : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gst: null;
} | {
    itr: null;
} | {
    legalDisputes: null;
} | {
    siteVisitNotes: null;
} | {
    ratingReport: null;
} | {
    boardMinutes: null;
} | {
    financialStatements: null;
} | {
    managementInterviewNotes: null;
} | {
    shareholdingPattern: null;
} | {
    annualReport: null;
} | {
    newsIntelligence: null;
} | {
    bankStatements: null;
} | {
    mcaFilings: null;
}): SourceCategory {
    return "gst" in value ? SourceCategory.gst : "itr" in value ? SourceCategory.itr : "legalDisputes" in value ? SourceCategory.legalDisputes : "siteVisitNotes" in value ? SourceCategory.siteVisitNotes : "ratingReport" in value ? SourceCategory.ratingReport : "boardMinutes" in value ? SourceCategory.boardMinutes : "financialStatements" in value ? SourceCategory.financialStatements : "managementInterviewNotes" in value ? SourceCategory.managementInterviewNotes : "shareholdingPattern" in value ? SourceCategory.shareholdingPattern : "annualReport" in value ? SourceCategory.annualReport : "newsIntelligence" in value ? SourceCategory.newsIntelligence : "bankStatements" in value ? SourceCategory.bankStatements : "mcaFilings" in value ? SourceCategory.mcaFilings : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CreditCase>): Array<CreditCase> {
    return value.map((x)=>from_candid_CreditCase_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EarlyWarningSignal>): Array<EarlyWarningSignal> {
    return value.map((x)=>from_candid_EarlyWarningSignal_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SourceStatus>): Array<SourceStatus> {
    return value.map((x)=>from_candid_SourceStatus_n43(_uploadFile, _downloadFile, x));
}
function to_candid_CAMReport_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CAMReport): _CAMReport {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_CaseStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseStatus): _CaseStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_CreditScore_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreditScore): _CreditScore {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_DataIngestionStatus_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DataIngestionStatus): _DataIngestionStatus {
    return to_candid_record_n71(_uploadFile, _downloadFile, value);
}
function to_candid_EarlyWarningSignal_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EarlyWarningSignal): _EarlyWarningSignal {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid_Recommendation_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Recommendation): _Recommendation {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function to_candid_RiskBand_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskBand): _RiskBand {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_Sector_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sector): _Sector {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Severity_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): _Severity {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function to_candid_SignalCategory_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalCategory): _SignalCategory {
    return to_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function to_candid_SourceCategory_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SourceCategory): _SourceCategory {
    return to_candid_variant_n78(_uploadFile, _downloadFile, value);
}
function to_candid_SourceStatusEnum_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SourceStatusEnum): _SourceStatusEnum {
    return to_candid_variant_n76(_uploadFile, _downloadFile, value);
}
function to_candid_SourceStatus_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SourceStatus): _SourceStatus {
    return to_candid_record_n74(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<EarlyWarningSignal> | null): [] | [Array<_EarlyWarningSignal>] {
    return value === null ? candid_none() : candid_some(to_candid_vec_n59(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    roe: number;
    netProfitMargin: number;
    overallScore: bigint;
    currentRatio: number;
    interestCoverageRatio: number;
    dscr: number;
    riskBand: RiskBand;
    managementQuality: bigint;
    debtToEquity: number;
    legalRiskScore: bigint;
    industryOutlook: bigint;
    complianceScore: bigint;
    financialHealth: bigint;
}): {
    roe: number;
    netProfitMargin: number;
    overallScore: bigint;
    currentRatio: number;
    interestCoverageRatio: number;
    dscr: number;
    riskBand: _RiskBand;
    managementQuality: bigint;
    debtToEquity: number;
    legalRiskScore: bigint;
    industryOutlook: bigint;
    complianceScore: bigint;
    financialHealth: bigint;
} {
    return {
        roe: value.roe,
        netProfitMargin: value.netProfitMargin,
        overallScore: value.overallScore,
        currentRatio: value.currentRatio,
        interestCoverageRatio: value.interestCoverageRatio,
        dscr: value.dscr,
        riskBand: to_candid_RiskBand_n56(_uploadFile, _downloadFile, value.riskBand),
        managementQuality: value.managementQuality,
        debtToEquity: value.debtToEquity,
        legalRiskScore: value.legalRiskScore,
        industryOutlook: value.industryOutlook,
        complianceScore: value.complianceScore,
        financialHealth: value.financialHealth
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description: string;
    category: SignalCategory;
    severity: Severity;
    detectedDate: Time;
}): {
    description: string;
    category: _SignalCategory;
    severity: _Severity;
    detectedDate: _Time;
} {
    return {
        description: value.description,
        category: to_candid_SignalCategory_n62(_uploadFile, _downloadFile, value.category),
        severity: to_candid_Severity_n64(_uploadFile, _downloadFile, value.severity),
        detectedDate: value.detectedDate
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    keyStrengths: Array<string>;
    keyRisks: Array<string>;
    recommendedLimitCrores: bigint;
    interestRateMax: number;
    interestRateMin: number;
    executiveSummary: string;
    riskPremiumBps: bigint;
    conditions: Array<string>;
    recommendation: Recommendation;
}): {
    keyStrengths: Array<string>;
    keyRisks: Array<string>;
    recommendedLimitCrores: bigint;
    interestRateMax: number;
    interestRateMin: number;
    executiveSummary: string;
    riskPremiumBps: bigint;
    conditions: Array<string>;
    recommendation: _Recommendation;
} {
    return {
        keyStrengths: value.keyStrengths,
        keyRisks: value.keyRisks,
        recommendedLimitCrores: value.recommendedLimitCrores,
        interestRateMax: value.interestRateMax,
        interestRateMin: value.interestRateMin,
        executiveSummary: value.executiveSummary,
        riskPremiumBps: value.riskPremiumBps,
        conditions: value.conditions,
        recommendation: to_candid_Recommendation_n68(_uploadFile, _downloadFile, value.recommendation)
    };
}
function to_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    filings: Array<SourceStatus>;
}): {
    filings: Array<_SourceStatus>;
} {
    return {
        filings: to_candid_vec_n72(_uploadFile, _downloadFile, value.filings)
    };
}
function to_candid_record_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: SourceStatusEnum;
    name: SourceCategory;
    notes?: string;
}): {
    status: _SourceStatusEnum;
    name: _SourceCategory;
    notes: [] | [string];
} {
    return {
        status: to_candid_SourceStatusEnum_n75(_uploadFile, _downloadFile, value.status),
        name: to_candid_SourceCategory_n77(_uploadFile, _downloadFile, value.name),
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseStatus): {
    completed: null;
} | {
    rejected: null;
} | {
    dataIngestion: null;
} | {
    analysis: null;
} | {
    draft: null;
} {
    return value == CaseStatus.completed ? {
        completed: null
    } : value == CaseStatus.rejected ? {
        rejected: null
    } : value == CaseStatus.dataIngestion ? {
        dataIngestion: null
    } : value == CaseStatus.analysis ? {
        analysis: null
    } : value == CaseStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sector): {
    it: null;
} | {
    realEstate: null;
} | {
    auto: null;
} | {
    fmcg: null;
} | {
    chemicals: null;
} | {
    steel: null;
} | {
    infrastructure: null;
} | {
    textile: null;
} | {
    pharma: null;
} {
    return value == Sector.it ? {
        it: null
    } : value == Sector.realEstate ? {
        realEstate: null
    } : value == Sector.auto ? {
        auto: null
    } : value == Sector.fmcg ? {
        fmcg: null
    } : value == Sector.chemicals ? {
        chemicals: null
    } : value == Sector.steel ? {
        steel: null
    } : value == Sector.infrastructure ? {
        infrastructure: null
    } : value == Sector.textile ? {
        textile: null
    } : value == Sector.pharma ? {
        pharma: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskBand): {
    a: null;
} | {
    b: null;
} | {
    d: null;
} | {
    aa: null;
} | {
    bb: null;
} | {
    aaa: null;
} | {
    bbb: null;
} | {
    ccc: null;
} {
    return value == RiskBand.a ? {
        a: null
    } : value == RiskBand.b ? {
        b: null
    } : value == RiskBand.d ? {
        d: null
    } : value == RiskBand.aa ? {
        aa: null
    } : value == RiskBand.bb ? {
        bb: null
    } : value == RiskBand.aaa ? {
        aaa: null
    } : value == RiskBand.bbb ? {
        bbb: null
    } : value == RiskBand.ccc ? {
        ccc: null
    } : value;
}
function to_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalCategory): {
    compliance: null;
} | {
    legal: null;
} | {
    market: null;
} | {
    financial: null;
} | {
    management: null;
} {
    return value == SignalCategory.compliance ? {
        compliance: null
    } : value == SignalCategory.legal ? {
        legal: null
    } : value == SignalCategory.market ? {
        market: null
    } : value == SignalCategory.financial ? {
        financial: null
    } : value == SignalCategory.management ? {
        management: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == Severity.low ? {
        low: null
    } : value == Severity.high ? {
        high: null
    } : value == Severity.critical ? {
        critical: null
    } : value == Severity.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Recommendation): {
    reject: null;
} | {
    approve: null;
} | {
    conditionalApprove: null;
} {
    return value == Recommendation.reject ? {
        reject: null
    } : value == Recommendation.approve ? {
        approve: null
    } : value == Recommendation.conditionalApprove ? {
        conditionalApprove: null
    } : value;
}
function to_candid_variant_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SourceStatusEnum): {
    pending: null;
} | {
    done: null;
} | {
    error: null;
} | {
    uploaded: null;
} | {
    processing: null;
} {
    return value == SourceStatusEnum.pending ? {
        pending: null
    } : value == SourceStatusEnum.done ? {
        done: null
    } : value == SourceStatusEnum.error ? {
        error: null
    } : value == SourceStatusEnum.uploaded ? {
        uploaded: null
    } : value == SourceStatusEnum.processing ? {
        processing: null
    } : value;
}
function to_candid_variant_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SourceCategory): {
    gst: null;
} | {
    itr: null;
} | {
    legalDisputes: null;
} | {
    siteVisitNotes: null;
} | {
    ratingReport: null;
} | {
    boardMinutes: null;
} | {
    financialStatements: null;
} | {
    managementInterviewNotes: null;
} | {
    shareholdingPattern: null;
} | {
    annualReport: null;
} | {
    newsIntelligence: null;
} | {
    bankStatements: null;
} | {
    mcaFilings: null;
} {
    return value == SourceCategory.gst ? {
        gst: null
    } : value == SourceCategory.itr ? {
        itr: null
    } : value == SourceCategory.legalDisputes ? {
        legalDisputes: null
    } : value == SourceCategory.siteVisitNotes ? {
        siteVisitNotes: null
    } : value == SourceCategory.ratingReport ? {
        ratingReport: null
    } : value == SourceCategory.boardMinutes ? {
        boardMinutes: null
    } : value == SourceCategory.financialStatements ? {
        financialStatements: null
    } : value == SourceCategory.managementInterviewNotes ? {
        managementInterviewNotes: null
    } : value == SourceCategory.shareholdingPattern ? {
        shareholdingPattern: null
    } : value == SourceCategory.annualReport ? {
        annualReport: null
    } : value == SourceCategory.newsIntelligence ? {
        newsIntelligence: null
    } : value == SourceCategory.bankStatements ? {
        bankStatements: null
    } : value == SourceCategory.mcaFilings ? {
        mcaFilings: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<EarlyWarningSignal>): Array<_EarlyWarningSignal> {
    return value.map((x)=>to_candid_EarlyWarningSignal_n60(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SourceStatus>): Array<_SourceStatus> {
    return value.map((x)=>to_candid_SourceStatus_n73(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
